FROM python:3.12-slim

RUN apt update && apt install -y gcc libpq-dev ffmpeg 

# Installation des dépendances
WORKDIR /webapp
COPY ./src/webapp/pyproject.toml .
RUN pip3 install poetry==1.8.3 

RUN poetry install

# Copier le reste du code
COPY ./src/webapp .
COPY .env .

# Exposer le port de FastAPI
EXPOSE 80

# Lancer l'application FastAPI
CMD ["tail", "-f", "/dev/null"]