FROM python:3.10-slim

RUN apt update && apt install -y gcc libpq-dev 
# Installation des dépendances
WORKDIR /api
COPY ./src/api/pyproject.toml .
RUN pip3 install poetry==1.8.3 

RUN poetry install

# Copier le reste du code
COPY ./src/api .
COPY .env .

# Exposer le port de FastAPI
EXPOSE 8000

# Lancer l'application FastAPI
CMD ["tail", "-f", "/dev/null"]